### ISSUE TITLE
reorganize the files / folders hierarchy

### ISSUE THREAD

**Issue by saidelike** [fidgetingbits/talon-vim#2]
- [ ] separate into different folders: apps, core, test, docs
- [ ] apps: gdb
- [ ] core: terminal, modes, rpc, title, 
- [ ] test
- [ ] docs
- [ ] clean separation between implementation and spoken forms similarly to https://github.com/AndreasArvidsson/andreas-talon

**Comment by fidgetingbits** [comment]
This is no longer relevant to this repo since you will use neovim-talon now, so closing
