### ISSUE TITLE
name vim actions internally different to spoken forms

### ISSUE THREAD

**Issue by saidelike** [fidgetingbits/talon-vim#3]
name functions and stuff internally similarly to Cursorless namings in order to differentiate the actions and the actual internals

eg `bring, replaceWithTarget` where we differentiate the bring command with the actual implementation. not that in our case we don't actually replace with a target, but instead we would bring to the current position so something like bringToCurrentPosition would be more appropriate

**Comment by fidgetingbits** [comment]
No longer relevant since cursorless works now
